//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.06 at 10:09:16 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://exemplo.com/wsdlservidor/assets", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.exemplo.wsdlservidor.assets;
